# NumPy

### Numpy, which stands for Numerical Python.
### ndarray is core object of NumPy

# Basic ndarray

#### Multi-Dimensional array
#### Homogeneous collection of values
#### Fast and Efficient
#### Support for mathematical functions
#### Primary container for data exchange between python algorithms

# Important attributes of an ndarray object are:

#### ndarray.ndim: The number of axes(dimensions) of the array.
#### ndarray.shape: The dimension of the array in form of (n,m).
#### ndarray.size: The total number elements of the array(n*m) 
#### ndarray.dtype:An object describing the type of the elements in the array.

In [1]:
import numpy as np
import matplotlib.pyplot as plt

# Create A Python Numpy Array Object from A Python List Object

In [3]:
lst=[0, 1, 2, 3]
a = np.array(lst)

In [6]:
print(lst)
print(type(lst))

[0, 1, 2, 3]
<class 'list'>


In [7]:
print(a)
print(type(a))

[0 1 2 3]
<class 'numpy.ndarray'>


# Bad Practice

In [ ]:
a=np.array(1,2,3,4) # Wrong
a=np.array([1,2,3,4]) # Right

# Type Casting

In [8]:
l=[1,2,3.0]
print(l)

[1, 2, 3.0]


In [10]:
a=np.array(l)
print(a) # Everything will get auto typecast in float because of higher priority in typecast. 
         # Similary if string present everything will get casted into string(Example below).
         # Type Precedence : Bool, Int, Float, String

[1. 2. 3.]


In [11]:
l=[1,2,"3.0"]
print(l)
a=np.array(l)
print(a)

[1, 2, '3.0']
['1' '2' '3.0']


In [13]:
print(np.array([1,2,3],dtype=float))
print(np.array([1,2,3],dtype='U'))
print(np.array([123456,2,3],dtype='U2'))
print(np.array([1,2,3],dtype=complex))

[1. 2. 3.]
['1' '2' '3']
['12' '2' '3']
[1.+0.j 2.+0.j 3.+0.j]


In [17]:
x=np.array([('Ram',26,1000.0),('Shyam',21,50000)],dtype=[('name','<U11'),('age','int32'),('salary','<f4')])
print(x)
print('Row 1',x[0])
print('Row 2',x[1])

[('Ram', 26,  1000.) ('Shyam', 21, 50000.)]
Row 1 ('Ram', 26, 1000.)
Row 2 ('Shyam', 21, 50000.)


In [9]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


**Why it is useful:** Memory-efficient container that provides fast numerical operations.

In [16]:
#python lists
L = range(1000)
%timeit [i**2 for i in L]  

584 µs ± 44.7 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [17]:
a = np.arange(1000)
%timeit a**2

2.22 µs ± 213 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


# 1. Creating Arrays

**1.1.  Manual Construction of arrays**

In [10]:
#1-D
a = np.array([0, 1, 2, 3])
a

array([0, 1, 2, 3])

In [11]:
#print dimensions
a.ndim

1

In [12]:
#shape
a.shape

(4,)

In [13]:
len(a)

4

In [22]:
# 2-D, 3-D....
b = np.array([[0, 1, 2], [3, 4, 5]])
b

array([[0, 1, 2],
       [3, 4, 5]])

In [23]:
b.ndim

2

In [24]:
b.shape

(2, 3)

In [25]:
len(b) #returns the size of the first dimention

2

In [19]:
c = np.array([[[0, 1], [2, 3]], 
              [[4, 5], [6, 7]]
             ])
c

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [17]:
c.ndim

1

In [18]:
c.shape

(2,)

**1.2  Functions for creating arrays**

In [29]:
#using arrange function

# arange is an array-valued version of the built-in Python range function

a = np.arange(10) # 0.... n-1
print(a)
print(type(a))
b = np.arange(1, 10, 2) #start(inclusive), end (exclusive), step
print(b)
print(type(b))

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
[1 3 5 7 9]
<class 'numpy.ndarray'>


In [30]:
#using linspace
a = np.linspace(0, 1, 6) #start(inclusive), end(exclusive), number of points
print(a)
print(type(a))

[0.  0.2 0.4 0.6 0.8 1. ]
<class 'numpy.ndarray'>


In [34]:
#common arrays
a = np.ones((3, 3)) # return a n dimensional array as per argument provided (x) 1-D, (x,y) 2D, (x,y,z) 3D,........ 
print(a)
type(a)
print(a.ndim)
print(a.shape)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
2
(3, 3)


In [35]:
b = np.zeros((3, 3))  # return a n dimensional array as per argument provided (x) 1-D, (x,y) 2D, (x,y,z) 3D,........
print(b)
type(b)
print(b.ndim)
print(b.shape)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
2
(3, 3)


In [0]:
c = np.eye(3)  #Return a 2-D array with ones on the diagonal and zeros elsewhere.
c

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [0]:
d = np.eye(3, 2) #3 is number of rows, 2 is number of columns, index of diagonal start with 0
d

array([[ 1.,  0.],
       [ 0.,  1.],
       [ 0.,  0.]])

In [0]:
#create array using diag function
a = np.diag([1, 2, 3, 4]) #construct a diagonal array.
a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [0]:
np.diag(a)   #Extract diagonal

array([1, 2, 3, 4])

In [42]:
#create array using random
#Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1).
a = np.random.rand(4) 
a

array([0.92356428, 0.46775518, 0.2320509 , 0.60939848])

In [41]:
a = np.random.randn(4)#Return a sample (or samples) from the “standard normal” distribution.  ***Gausian***
a

array([-0.00451859,  0.80698856,  0.93414123, -0.29873913])

**Note:**
    
For random samples from N(\mu, \sigma^2), use:

sigma * np.random.randn(...) + mu



# 2. Basic DataTypes

You may have noticed that, in some instances, array elements are displayed with a **trailing dot (e.g. 2. vs 2)**. This is due to a difference in the **data-type** used:

In [0]:
a = np.arange(10)
a.dtype

dtype('int64')

In [43]:
#You can explicitly specify which data-type you want:
a = np.arange(10, dtype='float64')
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [46]:
#The default data type is float for zeros and ones function
a = np.zeros((3, 3))
print(a)
a.dtype

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


dtype('float64')

**other datatypes**

In [47]:
d = np.array([1+2j, 2+4j])   #Complex datatype
print(d)
print(d.ndim)
print(d.shape)
print(d.dtype)

[1.+2.j 2.+4.j]
1
(2,)
complex128


In [48]:
b = np.array([True, False, True, False])  #Boolean datatype
print(b)
print(b.dtype)

[ True False  True False]
bool


In [50]:
s = np.array(['Ram', 'Robert', 'Rahim'])
print(s)
s.dtype

['Ram' 'Robert' 'Rahim']


dtype('<U6')

**Each built-in data type has a character code that uniquely identifies it.**

'b' − boolean

'i' − (signed) integer

'u' − unsigned integer

'f' − floating-point

'c' − complex-floating point

'm' − timedelta

'M' − datetime

'O' − (Python) objects

'S', 'a' − (byte-)string

'U' − Unicode

'V' − raw data (void)

**For more details**

**https://docs.scipy.org/doc/numpy-1.10.1/user/basics.types.html**

# 3. Indexing and Slicing

**3.1 Indexing**

The items of an array can be accessed and assigned to the same way as other **Python sequences (e.g. lists)**:

In [0]:
a = np.arange(10)

print(a[5])  #indices begin at 0, like other Python sequences (and C/C++)

5


In [52]:
# For multidimensional arrays, indexes are tuples of integers:
a = np.diag([1, 2, 3])
print(a[2, 2])

3


In [53]:
a[2, 1] = 5 #assigning value
a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 5, 3]])

**3.2 Slicing**

In [0]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
a[1:8:2] # [startindex: endindex(exclusive) : step]

array([1, 3, 5, 7])

In [56]:
#we can also combine assignment and slicing:
a = np.arange(10)
a[5:] = 10
print(a)

[ 0  1  2  3  4 10 10 10 10 10]


In [57]:
b = np.arange(5)
print(b)
a[5:] = b[::-1]  #assigning
print(a)

[0 1 2 3 4]
[0 1 2 3 4 4 3 2 1 0]


# 4. Copies and Views

A slicing operation creates a view on the original array, which is just a way of accessing array data. Thus the original array is not copied in memory. You can use **np.may_share_memory()** to check if two arrays share the same memory block. 

**When modifying the view, the original array is modified as well:**

In [0]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
b = a[::2]
b

array([0, 2, 4, 6, 8])

In [0]:
np.shares_memory(a, b)

True

In [0]:
b[0] = 10
b

array([10,  2,  4,  6,  8])

In [0]:
a  #eventhough we modified b,  it updated 'a' because both shares same memory

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [0]:
a = np.arange(10)
c = a[::2].copy()     #force a copy
c

array([0, 2, 4, 6, 8])

In [0]:
np.shares_memory(a, c)

False

In [0]:
c[0] = 10
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# 5. Fancy Indexing

NumPy arrays can be indexed with slices, but also with boolean or integer arrays **(masks)**. This method is called **fancy indexing**. It creates copies not views.

**Using Boolean Mask**

In [0]:
a = np.random.randint(0, 20, 15)
a

array([18, 17,  1, 18,  5, 17,  0, 14, 12, 11,  4, 15, 16,  8,  7])

In [0]:
mask = (a % 2 == 0)

In [0]:
extract_from_a = a[mask]

extract_from_a

array([18, 18,  0, 14, 12,  4, 16,  8])

**Indexing with a mask can be very useful to assign a new value to a sub-array:**

In [0]:
a[mask] = -1
a

array([-1, 17,  1, -1,  5, 17, -1, -1, -1, 11, -1, 15, -1, -1,  7])

**Indexing with an array of integers**

In [0]:
a = np.arange(0, 100, 10)
a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [0]:
#Indexing can be done with an array of integers, where the same index is repeated several time:
a[[2, 3, 2, 4, 2]]

array([20, 30, 20, 40, 20])

In [0]:
# New values can be assigned 
a[[9, 7]] = -200
a

array([   0,   10,   20,   30,   40,   50,   60, -200,   80, -200])

# Elementwise Operations

**1. Basic Operations**

**with scalars**

In [58]:
a = np.array([1, 2, 3, 4]) #create an array
a + 1

array([2, 3, 4, 5])

In [59]:
a ** 2

array([ 1,  4,  9, 16], dtype=int32)

**All arithmetic operates elementwise**

In [60]:
b = np.ones(4) + 1
a - b

array([-1.,  0.,  1.,  2.])

In [61]:
a * b

array([2., 4., 6., 8.])

In [62]:
# Matrix multiplication

c = np.diag([1, 2, 3, 4])

print(c * c)
print("*****************")
print(c.dot(c))

[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]
*****************
[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


**comparisions**

In [63]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 2, 2, 4])
a == b

array([False,  True, False,  True])

In [64]:
a > b

array([False, False,  True, False])

In [ ]:
#array-wise comparisions
a = np.array([1, 2, 3, 4])
b = np.array([5, 2, 2, 4])
c = np.array([1, 2, 3, 4])

np.array_equal(a, b)

In [ ]:
np.array_equal(a, c)

**Logical Operations**

In [ ]:
a = np.array([1, 1, 0, 0], dtype=bool)
b = np.array([1, 0, 1, 0], dtype=bool)

np.logical_or(a, b)

In [ ]:
np.logical_and(a, b)

**Transcendental functions:**

In [69]:
a = np.arange(5)
np.sin(a)  

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [ ]:
np.log(a)

In [ ]:
np.exp(a)   #evaluates e^x for each element in a given input

In [ ]:
**Shape Mismatch**

In [70]:
a = np.arange(4)
a + np.array([1, 2])

ValueError: operands could not be broadcast together with shapes (4,) (2,) 

# Basic Reductions

**computing sums**

In [ ]:
x = np.array([1, 2, 3, 4])
np.sum(x)

In [72]:
#sum by rows and by columns

x = np.array([[1, 1], [2, 2]])
x

array([[1, 1],
       [2, 2]])

In [73]:
x.sum(axis=0)   #columns first dimension

array([3, 3])

In [74]:
x.sum(axis=1)  #rows (second dimension)

array([2, 4])

**Other reductions**

In [ ]:
x = np.array([1, 3, 2])
x.min()

In [ ]:
x.max()

In [ ]:
x.argmin()# index of minimum element

In [ ]:
x.argmax()# index of maximum element

**Logical Operations**

In [ ]:
np.all([True, True, False])

In [ ]:
np.any([True, False, False])

In [ ]:
#Note: can be used for array comparisions
a = np.zeros((50, 50))
np.any(a != 0)

In [ ]:
np.all(a == a)

In [ ]:
a = np.array([1, 2, 3, 2])
b = np.array([2, 2, 3, 2])
c = np.array([6, 4, 4, 5])
((a <= b) & (b <= c)).all()

**Statistics**

In [ ]:
x = np.array([1, 2, 3, 1])
y = np.array([[1, 2, 3], [5, 6, 1]])
x.mean()

In [ ]:
np.median(x)

In [ ]:
np.median(y, axis=-1) # last axis

In [ ]:
x.std() # full population standard dev.

**Example:**

Data in populations.txt describes the populations of hares and lynxes (and carrots) in northern Canada during 20 years.

In [ ]:
#load data into numpy array object
data = np.loadtxt('populations.txt')

In [ ]:
data

In [ ]:
year, hares, lynxes, carrots = data.T #columns to variables
print(year)

In [ ]:
#The mean population over time
populations = data[:, 1:]
populations

In [ ]:
#sample standard deviations
populations.std(axis=0)

In [ ]:
#which species has the highest population each year?
np.argmax(populations, axis=1)

# Broadcasting

Basic operations on numpy arrays (addition, etc.) are elementwise

This works on arrays of the same size.
    Nevertheless, It’s also possible to do operations on arrays of different sizes if NumPy can transform these arrays     so that they all have the same size: this conversion is called broadcasting.

The image below gives an example of broadcasting:

In [ ]:
![title](broadcasting.png)

In [ ]:
a = np.tile(np.arange(0, 40, 10), (3,1))
print(a)

print("*************")
a=a.T
print(a)

In [ ]:

b = np.array([0, 1, 2])
b

In [ ]:
a + b

In [ ]:
a = np.arange(0, 40, 10)
a.shape


In [ ]:
a = a[:, np.newaxis]  # adds a new axis -> 2D array
a.shape

In [ ]:
a

In [ ]:
a + b

# Array Shape Manipulation

**Flattening**

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a.ravel() #Return a contiguous flattened array. A 1-D array, containing the elements of the input, is returned. A copy is made only if needed.

In [ ]:
a.T #Transpose

In [ ]:
a.T.ravel()

**Reshaping**

The inverse operation to flattening:

In [ ]:
print(a.shape)
print(a)

In [ ]:
b = a.ravel()
print(b)

In [ ]:
b = b.reshape((2, 3))
b

In [ ]:
b[0, 0] = 100
a

**Note and       Beware: reshape may also return a copy!:**

In [ ]:
a = np.zeros((3, 2))
b = a.T.reshape(3*2)
b[0] = 50
a

**Adding a Dimension**

Indexing with the np.newaxis object allows us to add an axis to an array

newaxis is used to increase the dimension of the existing array by one more dimension, when used once. Thus,

1D array will become 2D array

2D array will become 3D array

3D array will become 4D array and so on

In [ ]:
z = np.array([1, 2, 3])
z

In [ ]:
z[:, np.newaxis]

**Dimension Shuffling**

In [ ]:
a = np.arange(4*3*2).reshape(4, 3, 2)
a.shape

In [ ]:
a

In [ ]:
a[0, 2, 1]

**Resizing**

In [ ]:
a = np.arange(4)
a.resize((8,))
a

However, it must not be referred to somewhere else:

In [ ]:
b = a
a.resize((4,)) 

**Sorting Data**

In [ ]:
#Sorting along an axis:
a = np.array([[5, 4, 6], [2, 3, 2]])
b = np.sort(a, axis=1)
b

In [ ]:
#in-place sort
a.sort(axis=1)
a

In [ ]:
#sorting with fancy indexing
a = np.array([4, 3, 1, 2])
j = np.argsort(a)
j

In [ ]:
a[j]