In [1]:
from numpy import random
import numpy as np

In [2]:
random.rand(5)

array([0.861425  , 0.1150514 , 0.23599136, 0.56019093, 0.21399814])

In [13]:
random.rand(2,3)

array([[0.48928937, 0.58720285, 0.70378543],
       [0.21116838, 0.10076265, 0.97633529]])

In [14]:
random.rand(2,3,2)

array([[[0.30398232, 0.27174439],
        [0.21152153, 0.85714101],
        [0.64718068, 0.13355733]],

       [[0.85187783, 0.06863756],
        [0.75214553, 0.71232343],
        [0.69222323, 0.80281379]]])

In [36]:
random.randn(36).mean()

0.007704445322658614

In [28]:
random.randn(35).std()

1.187738801612515

In [50]:
arr=random.randn(30,3)

In [62]:
i=arr.shape[0]
j=arr.shape[1]

In [104]:
random.randint(10,25,5)

array([24, 12, 19, 14, 16])

In [105]:
random.sample(10)

array([0.30806554, 0.20023647, 0.31307236, 0.74292204, 0.07105788,
       0.80433434, 0.99619276, 0.80849917, 0.45178165, 0.75614615])

In [106]:
random.random(10)

array([0.09191729, 0.04692225, 0.58597747, 0.93416307, 0.60436639,
       0.7126722 , 0.74599893, 0.64224423, 0.21536222, 0.41145899])

In [112]:
a=np.arange(10)

In [120]:
random.choice(a,size=5,replace=True)

array([2, 3, 1, 9, 1])

In [127]:
random.standard_normal(31).mean()

-0.16900223334972148

In [137]:
np.arange(10).dtype

dtype('int32')

In [151]:
a=[[1,2,3],[4,5,6]]
np.ones_like(a,dtype="int64")

array([[1, 1, 1],
       [1, 1, 1]], dtype=int64)

In [160]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])